spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/trading"
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092


cors:
  allowed:
    origin: "http://localhost:3000"